# Path to your oh-my-zsh installation.
export ZSH="$HOME/.oh-my-zsh"

# Default theme
ZSH_THEME="avit-arrow"

# Use case-sensitive completion.
CASE_SENSITIVE="true"

# Load Plugins
plugins=(git zsh-completions zsh-autosuggestions zsh-syntax-highlighting)

source $ZSH/oh-my-zsh.sh

# Setup Locale, change it to your default locale
export LANG=en_US.UTF-8
export LC_ALL=en_US.UTF-8

# Setup PATH
export PATH="$HOME/.rbenv/bin:$PATH"
export PATH="/usr/lib/go-1.15/bin:$PATH"
export PATH="$HOME/.local/bin:$PATH"
# Add any custom paths to `PATH` below

# Setup SSH agent
eval "$(ssh-agent -s)" > /dev/null

# Setup rbenv
eval "$(rbenv init -)"

# Setup Homebrew for Linux
eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"

# Add SSH Keys
# Update and uncomment following line for each keypair.
# ssh-add -q ~/.ssh/id_rsa