# Path to your Oh-my-zsh installation.
export ZSH="$HOME/.oh-my-zsh"

# Default theme
ZSH_THEME="avit-arrow"

# Use case-sensitive completion.
CASE_SENSITIVE="true"

# Load Oh-my-zsh Plugins
plugins=(git zsh-completions zsh-autosuggestions zsh-syntax-highlighting)

source $ZSH/oh-my-zsh.sh

# Setup PATH
export PATH="$HOME/.rbenv/bin:$PATH"
export PATH="$HOME/.local/bin:$PATH"

# Setup Binaries
eval "$(rbenv init -)"
eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"